table JobSkills
	lineageTag: eb1aa5c2-aa76-4c87-abcd-3915767194c4

	column Value
		dataType: string
		lineageTag: 20058160-56f7-44b1-8eb0-0ecef963001f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: a12a7583-a8b7-4042-b3a9-eb983a669dfa
		summarizeBy: none
		sourceColumn: job_id

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: int64
		formatString: 0
		lineageTag: 21eccebc-fe66-469d-8520-264e2aff7324
		summarizeBy: sum
		sourceColumn: company_id

		annotation SummarizationSetBy = Automatic

	partition JobSkills = m
		mode: import
		source =
				let
				    Source = job_postings_fact,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"job_title_short", "job_title", "job_location", "job_via", "job_schedule_type", "job_work_from_home", "search_location", "job_posted_date", "job_no_degree_mention", "job_health_insurance", "job_country", "salary_rate", "salary_year_avg", "salary_hour_avg", "WeekDay"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","[","",Replacer.ReplaceText,{"job_skills"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","]","",Replacer.ReplaceText,{"job_skills"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","'","",Replacer.ReplaceText,{"job_skills"}),
				    #"Trimmed Text" = Table.TransformColumns(#"Replaced Value2",{{"job_skills", Text.Trim, type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Trimmed Text", "job_skills", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"job_skills.1", "job_skills.2", "job_skills.3", "job_skills.4", "job_skills.5", "job_skills.6", "job_skills.7", "job_skills.8", "job_skills.9", "job_skills.10", "job_skills.11", "job_skills.12", "job_skills.13", "job_skills.14", "job_skills.15", "job_skills.16"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"job_skills.1", type text}, {"job_skills.2", type text}, {"job_skills.3", type text}, {"job_skills.4", type text}, {"job_skills.5", type text}, {"job_skills.6", type text}, {"job_skills.7", type text}, {"job_skills.8", type text}, {"job_skills.9", type text}, {"job_skills.10", type text}, {"job_skills.11", type text}, {"job_skills.12", type text}, {"job_skills.13", type text}, {"job_skills.14", type text}, {"job_skills.15", type text}, {"job_skills.16", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type",{"job_type_skills"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns1", {"job_id", "company_id"}, "Attribute", "Value"),
				    #"Removed Columns2" = Table.RemoveColumns(#"Unpivoted Other Columns",{"Attribute"})
				in
				    #"Removed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

