table Sheet1
	lineageTag: 2f67beb9-434a-4516-99db-483730865776

	column job_title_short
		dataType: string
		lineageTag: 891c3d78-6c3e-42bc-b2cb-e0c2db9b93f1
		summarizeBy: none
		sourceColumn: job_title_short

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: 34d96b7a-f1a2-4cba-ac2a-d75d92ed8d32
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column job_location
		dataType: string
		lineageTag: 3ec8eba5-15e8-4f81-9a07-2dd942b33ac4
		summarizeBy: none
		sourceColumn: job_location

		annotation SummarizationSetBy = Automatic

	column job_via
		dataType: string
		lineageTag: 2da2dba8-aa48-4d50-93af-ec11092a0e6a
		summarizeBy: none
		sourceColumn: job_via

		annotation SummarizationSetBy = Automatic

	column job_schedule_type
		dataType: string
		lineageTag: 6b4f5d8c-c90e-4aaf-bda9-ddc9cdb986f9
		summarizeBy: none
		sourceColumn: job_schedule_type

		annotation SummarizationSetBy = Automatic

	column job_work_from_home
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0d85fd33-19ba-4c66-88d9-fba92ca57cfa
		summarizeBy: none
		sourceColumn: job_work_from_home

		annotation SummarizationSetBy = Automatic

	column search_location
		dataType: string
		lineageTag: 14823ba5-af45-4ab0-be1a-df1dfdc86551
		summarizeBy: none
		sourceColumn: search_location

		annotation SummarizationSetBy = Automatic

	column job_posted_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 53b9eba1-4a1b-499b-9ef6-6e85851fbed0
		summarizeBy: none
		sourceColumn: job_posted_date

		variation Variation
			isDefault
			relationship: 483287dd-73d5-4652-aa73-e2183883691b
			defaultHierarchy: LocalDateTable_7c1e3716-1a97-4cc4-bc92-d693fc0e249b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column job_no_degree_mention
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 66eb7038-75e9-4697-8c81-e55682d7cff4
		summarizeBy: none
		sourceColumn: job_no_degree_mention

		annotation SummarizationSetBy = Automatic

	column job_health_insurance
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ff47b9f4-bbe5-4eed-8c1e-f87bc6540cc4
		summarizeBy: none
		sourceColumn: job_health_insurance

		annotation SummarizationSetBy = Automatic

	column job_country
		dataType: string
		lineageTag: 5f87d814-3124-42bc-8eaf-6d3605f08de7
		summarizeBy: none
		sourceColumn: job_country

		annotation SummarizationSetBy = Automatic

	column salary_rate
		dataType: string
		lineageTag: 4a5b089d-be29-4a38-8eb0-efd47d0cdf92
		summarizeBy: none
		sourceColumn: salary_rate

		annotation SummarizationSetBy = Automatic

	column salary_year_avg
		dataType: int64
		formatString: 0
		lineageTag: 5f24bf8b-52f9-435c-afdb-b7bc8a65bb8e
		summarizeBy: sum
		sourceColumn: salary_year_avg

		annotation SummarizationSetBy = Automatic

	column salary_hour_avg
		dataType: double
		lineageTag: 560d3bc9-f139-40bf-830c-3041b4d8d633
		summarizeBy: sum
		sourceColumn: salary_hour_avg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column company_name
		dataType: string
		lineageTag: 06e88011-53cc-457d-b75a-17efe0f83a70
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	column job_skills
		dataType: string
		lineageTag: 20ddd9dc-2c3b-49c0-aaaf-18ea09140dcf
		summarizeBy: none
		sourceColumn: job_skills

		annotation SummarizationSetBy = Automatic

	column job_type_skills
		dataType: string
		lineageTag: 7fd3c825-c9b6-45ee-af3a-7414081bccd4
		summarizeBy: none
		sourceColumn: job_type_skills

		annotation SummarizationSetBy = Automatic

	column salary_hour_adj
		dataType: double
		lineageTag: f18caba5-3cdd-42e8-915f-79d8d822b200
		summarizeBy: sum
		sourceColumn: salary_hour_adj

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column salary_hr&yr
		dataType: string
		lineageTag: 3e46a804-3d65-4d36-8789-8ab3911627af
		summarizeBy: none
		sourceColumn: salary_hr&yr

		annotation SummarizationSetBy = Automatic

	column Date_Month = Sheet1[job_posted_date].[Month]
		lineageTag: 51ad8345-73e7-4eb2-9f9b-665c8e8426a2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Date_Day = FORMAT(Sheet1[job_posted_date].[Date], "dddd")
		lineageTag: b9d121a0-415e-4209-a377-23cd193ec00b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://docs.google.com/spreadsheets/d/e/2PACX-1vQQBMP11EWTJYN_BKDpE8LvMVEhXgv24xSSxt74hSO3kpOl4h5oEOatkQozCZ06wA/pub?output=xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_title_short", type text}, {"job_title", type text}, {"job_location", type text}, {"job_via", type text}, {"job_schedule_type", type text}, {"job_work_from_home", type logical}, {"search_location", type text}, {"job_posted_date", type number}, {"job_no_degree_mention", type logical}, {"job_health_insurance", type logical}, {"job_country", type text}, {"salary_rate", type text}, {"salary_year_avg", Int64.Type}, {"salary_hour_avg", type number}, {"company_name", type text}, {"job_skills", type text}, {"job_type_skills", type text}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type","via ","",Replacer.ReplaceText,{"job_via"}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Replaced Value1", "salary_hour_adj", each [salary_hour_avg] * 2080, type number),
				    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Multiplication",{"job_title_short", "job_title", "job_location", "job_via", "job_schedule_type", "job_work_from_home", "search_location", "job_posted_date", "job_no_degree_mention", "job_health_insurance", "job_country", "salary_rate", "salary_year_avg", "salary_hour_avg", "salary_hour_adj", "company_name", "job_skills", "job_type_skills"}),
				    #"Added Custom Column" = Table.AddColumn(#"Reordered Columns", "Custom", each Text.Combine({Text.From([salary_year_avg], "en-PH"), Text.From([salary_hour_adj], "en-PH")}), type text),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom Column",{"job_title_short", "job_title", "job_location", "job_via", "job_schedule_type", "job_work_from_home", "search_location", "job_posted_date", "job_no_degree_mention", "job_health_insurance", "job_country", "salary_rate", "salary_year_avg", "salary_hour_avg", "salary_hour_adj", "Custom", "company_name", "job_skills", "job_type_skills"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns1",{{"Custom", "salary_hr&yr"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([#"salary_hr&yr"] <> "")),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"job_posted_date", type datetime}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

